### ISSUE TITLE
Hyperledger Projects - Fabric card displayed twice

### ISSUE THREAD

**Issue by minyu66** [hyperledger-dlt-landscape/hyperledger-dlt-landscape#152]
- for Hyperledger Projects, there are two Hyperledger Fabric cards, one of them is Hyperledger Fabric, which is correct, the other is Chaincode, which is not a top-level Hyperledger project.
![Screenshot 2023-05-02 at 1 35 55 PM](https://user-images.githubusercontent.com/77464529/235755439-31e6eeae-d835-45be-8e4f-b5279516baa5.png)

**Comment by AndreyKozlov1984** [comment]
@ryjones @minyu66 which project Chaincode belongs to? If it is 
not graduated, then where should it be moved?

**Comment by ryjones** [comment]
@AndreyKozlov1984 Chaincode is not a project, it is something Fabric supports.

**Comment by ryjones** [comment]
@AndreyKozlov1984 it should appear [here](https://dltlandscape.org/card-mode?category=smart-contracts-tokenization) but not [here](https://dltlandscape.org/card-mode?project=hosted)

**Comment by AndreyKozlov1984** [comment]
I still don't know what you want to achieve:

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/230982/236253341-3c6e61d3-a1e0-408b-9599-2621a141a3b5.png">

Basically, on your link https://dltlandscape.org/card-mode?project=hosted you just applied an extra filter to specify the Category

**Comment by ryjones** [comment]
Chaincode is not a project, it is a feature of a project. It should not appear in the "graduated projects" group

**Comment by ryjones** [comment]
fixed
