### ISSUE TITLE
Japan Securities Clearing Corporation (JSCC)

### ISSUE THREAD

**Issue by minyu66** [hyperledger-dlt-landscape/hyperledger-dlt-landscape#240]
Japan Securities Clearing Corporation (JSCC)'s svg logo has been added to our CRM, membership is now active. But I am not seeing its logo on our landscape.

For I recall that I saw it in the preview of the "update member" over the weekend. Nonetheless, I don't see it in the preview log or on our current landscape. But everything in CRM is correctly entered.

@ryjones could you please look into this?

**Comment by ryjones** [comment]
@minyu66 I don't see it in any PRs or commits for the last week?

**Comment by minyu66** [comment]
I had to do something in Salesforce. Now I do see the PR. I will merge just in time for the new member announcement. Thanks, Ry!

**Comment by ryjones** [comment]
sure thing!
